import Header from "./components/Header";
import "./globals.css";

import { Nanum_Gothic } from "next/font/google";

const namun = Nanum_Gothic({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Howoo.C",
  description: "Generated by create next app",
  keywords: "howoo king",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ko'>
      <body className={namun.className}>
        <Header />
        <main className='container mx-auto bg-slate-200'>{children}</main>
      </body>
    </html>
  );
}
